"""Morning gap scanner: screens the S&P 500 universe (via free yfinance data,
no IBKR market-data subscription needed) for gappers above a minimum price
and gap %, and writes the top survivors to watchlist.txt for cycle.py to
trade against. Runs 7x every morning via Task Scheduler.
"""
import argparse
import json
import sys
import time
from datetime import datetime
from pathlib import Path
from zoneinfo import ZoneInfo

import yfinance as yf

from src.notify import notify
from src.sp500_tickers import SP500_TICKERS

WATCHLIST_PATH = Path("watchlist.txt")
DEFAULT_MIN_GAP_PCT = 3.0
DEFAULT_MIN_PRICE = 3.0
MAX_SURVIVORS = 20
ET = ZoneInfo("America/New_York")


def _ibkr_to_yahoo(ticker: str) -> str:
    return ticker.replace(" ", "-")


def _yahoo_to_ibkr(ticker: str) -> str:
    return ticker.replace("-", " ")


def run_scan(min_gap: float, min_price: float, dry_run: bool) -> dict:
    started = time.monotonic()
    yahoo_tickers = [_ibkr_to_yahoo(t) for t in SP500_TICKERS]

    data = yf.download(
        tickers=" ".join(yahoo_tickers),
        period="2d",
        interval="1d",
        group_by="ticker",
        threads=5,
        progress=False,
        auto_adjust=True,
    )

    if data.empty:
        result = {
            "success": False,
            "error": "yf.download returned an empty dataframe",
            "total_screened": len(SP500_TICKERS),
        }
        print(json.dumps(result))
        notify(
            f"Prefilter FAILED {datetime.now(ET).strftime('%H:%M')} ET",
            result["error"],
            "high",
        )
        return result

    survivors = []
    below_gap = 0
    below_price = 0
    failed = 0

    multi_ticker = len(SP500_TICKERS) > 1

    for ibkr_ticker, yahoo_ticker in zip(SP500_TICKERS, yahoo_tickers):
        try:
            bars = data[yahoo_ticker] if multi_ticker else data
            bars = bars.dropna(how="all")
            if len(bars) < 2:
                failed += 1
                continue

            yesterday_close = float(bars.iloc[-2]["Close"])
            today_close = float(bars.iloc[-1]["Close"])

            gap_pct = (today_close - yesterday_close) / yesterday_close * 100 if yesterday_close else 0.0

            price_ok = today_close >= min_price
            gap_ok = gap_pct >= min_gap

            if not price_ok:
                below_price += 1
                continue
            if not gap_ok:
                below_gap += 1
                continue

            survivors.append({
                "ticker": ibkr_ticker,
                "gap_pct": gap_pct,
                "open": float(bars.iloc[-1]["Open"]),
                "prev_close": yesterday_close,
            })
        except (KeyError, IndexError, ValueError):
            failed += 1
            continue

    survivors.sort(key=lambda s: s["gap_pct"], reverse=True)
    survivors = survivors[:MAX_SURVIVORS]

    total = len(SP500_TICKERS)
    elapsed = round(time.monotonic() - started, 2)
    now_et_str = datetime.now(ET).strftime("%Y-%m-%d %H:%M %Z")

    if not dry_run:
        WATCHLIST_PATH.parent.mkdir(parents=True, exist_ok=True)
        lines = [
            f"# Auto-generated by morning_prefilter.py at {now_et_str}",
            f"# Filters: gap >= {min_gap}%, price >= ${min_price}",
            "# Source: yfinance (screening only); IBKR handles execution",
            f"# Survivors: {len(survivors)} (capped at {MAX_SURVIVORS}) of {total}",
            "#",
            "# ticker  # gap +X.XX%  open $X.XX  prev $X.XX",
        ]
        for s in survivors:
            lines.append(
                f"{s['ticker']}  # gap {s['gap_pct']:+.2f}%  "
                f"open ${s['open']:.2f}  prev ${s['prev_close']:.2f}"
            )
        WATCHLIST_PATH.write_text("\n".join(lines) + "\n")

    top_20_survivors = [f"{s['ticker']} ({s['gap_pct']:+.2f}%)" for s in survivors]

    result = {
        "success": True,
        "total_screened": total,
        "survivors_count": len(survivors),
        "below_gap": below_gap,
        "below_price": below_price,
        "failed": failed,
        "elapsed_seconds": elapsed,
        "top_20_survivors": top_20_survivors,
        "watchlist_path": str(WATCHLIST_PATH),
    }
    print(json.dumps(result))

    if failed / total >= 0.95:
        print("ALERT: Yahoo-wide failure suspected; check yfinance changelog", file=sys.stderr)
    elif failed / total >= 0.30:
        print(f"ALERT: yfinance degradation (failed {failed}/{total})", file=sys.stderr)

    if not dry_run:
        if survivors:
            body = f"{len(survivors)}/{total} survivors in {elapsed}s\n" + "\n".join(
                f"- {s}" for s in top_20_survivors
            )
        else:
            body = f"0/{total} survivors in {elapsed}s"
        notify(f"Prefilter {datetime.now(ET).strftime('%H:%M')} ET", body, "default")

        if failed / total >= 0.30:
            notify(
                f"Prefilter degradation {datetime.now(ET).strftime('%H:%M')} ET",
                f"failed {failed}/{total} tickers",
                "high",
            )

    return result


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--min-gap", type=float, default=DEFAULT_MIN_GAP_PCT)
    parser.add_argument("--min-price", type=float, default=DEFAULT_MIN_PRICE)
    parser.add_argument("--dry-run", action="store_true")
    args = parser.parse_args()

    result = run_scan(args.min_gap, args.min_price, args.dry_run)
    sys.exit(0 if result.get("success") else 1)


if __name__ == "__main__":
    main()
