"""Provisions and controls a non-admin account's own IB Gateway + trading
engine — the instantiated systemd unit (deploy/ibgateway-live@.service),
one process pair per account, keyed by account_id (%i in the unit name).
The admin's own Gateway stays on the original fixed units (see
web/gateway_control.py) and is never touched by this module.

"Connect" (provision_and_connect) only starts the Gateway process, not the
trading engine — mirrors gateway_control.py's own reconnect_gateway()/
resume_engine() split: IBKR may need a fresh 2FA approval on THIS
account's own phone before the Gateway actually logs in, so the engine
should only start once status() shows port_listening=True.

Paper trading has been removed (see db.MODES' own comment) - this used to
provision a paper+live pair per account; now just live."""
from pathlib import Path

from src import db, secrets_store, systemd_util

PROJECT_DIR = Path(__file__).resolve().parent.parent
IBC_DIR = PROJECT_DIR / "deploy" / "ibc"

GATEWAY_UNIT = "ibgateway-live@{account_id}.service"
ENGINE_UNIT = "trading-bot-live@{account_id}.service"

ProvisioningError = systemd_util.SystemctlError


class CredentialsNotSetError(RuntimeError):
    """Raised when an account tries to connect before saving IBKR
    credentials — see web/app.py's /api/ibkr_credentials."""


class AdminNotAllowedError(RuntimeError):
    """The admin already has a working Gateway on the original fixed
    units (see web/gateway_control.py) — self-provisioning through here
    too would start a SECOND, redundant Gateway process logged into the
    exact same IBKR account, which IBKR would treat as a conflicting
    session. This path is for every other account only."""


def _check_not_admin(account_id: int):
    if account_id == db.get_default_account_id():
        raise AdminNotAllowedError(
            "The admin account already has a Gateway — use the Gateway Connection card instead."
        )


def _ibc_config_path(account_id: int, mode: str) -> Path:
    return IBC_DIR / f"config-{account_id}-{mode}.ini"


def _write_ibc_config(account_id: int, mode: str, ibkr_username: str, ibkr_password: str, port: int):
    # Regenerated on every Connect click — never hand-edited, so it's
    # always in sync with whatever credentials/port this account has on
    # file right now.
    content = f"""\
# Auto-generated by src/gateway_provisioning.py for account {account_id}
# ({mode}). Regenerated every time this account clicks Connect — do not
# edit by hand, changes will be overwritten on the next Connect.
IbLoginId={ibkr_username}
IbPassword={ibkr_password}
TradingMode={mode}
OverrideTwsApiPort={port}

AcceptIncomingConnectionAction=accept
AllowBlindTrading=no
ReadOnlyLogin=no
AcceptNonBrokerageAccountWarning=yes
DismissPasswordExpiryWarning=yes
DismissNSEComplianceNotice=yes
ExistingSessionDetectedAction=primary

# IBC can automate the username/password fields but cannot tap "Approve"
# on this account's own phone for a 2FA push — this just controls how
# long IBC waits for that before giving up.
SecondFactorAuthenticationTimeout=180
SecondFactorDevice=IB Key

LogComponents=open
"""
    path = _ibc_config_path(account_id, mode)
    path.write_text(content)
    path.chmod(0o600)


def provision_and_connect(account_id: int):
    """Writes this account's IBC config from their saved credentials and
    starts their Gateway process. Raises CredentialsNotSetError if they
    haven't saved IBKR credentials yet, or ProvisioningError if starting
    the unit fails (most likely the sudoers rules for @-instances haven't
    been installed on this server yet)."""
    _check_not_admin(account_id)
    creds = db.get_ibkr_credentials(account_id)
    if creds is None:
        raise CredentialsNotSetError("Save your IBKR username and password first.")

    ibkr_username = creds["ibkr_username"]
    ibkr_password = secrets_store.decrypt(creds["ibkr_password_encrypted"])
    ports = db.get_or_assign_gateway_ports(account_id)

    IBC_DIR.mkdir(parents=True, exist_ok=True)
    _write_ibc_config(account_id, "live", ibkr_username, ibkr_password, ports["live_port"])

    systemd_util.run_privileged("start", GATEWAY_UNIT.format(account_id=account_id))


def resume_engines(account_id: int):
    """Starts this account's trading engine — call only after status()
    shows port_listening=True (i.e. 2FA has actually been approved and
    the Gateway is really up)."""
    _check_not_admin(account_id)
    systemd_util.run_privileged("start", ENGINE_UNIT.format(account_id=account_id))


def disconnect(account_id: int):
    """Stops this account's engine first, then its Gateway — so the
    engine never sees its Gateway disappear out from under it mid-cycle."""
    _check_not_admin(account_id)
    systemd_util.run_privileged("stop", ENGINE_UNIT.format(account_id=account_id))
    systemd_util.run_privileged("stop", GATEWAY_UNIT.format(account_id=account_id))


def status(account_id: int) -> dict:
    _check_not_admin(account_id)
    ports = db.get_or_assign_gateway_ports(account_id)
    return {
        "live": {
            "gateway_active": systemd_util.is_active(GATEWAY_UNIT.format(account_id=account_id)),
            "engine_active": systemd_util.is_active(ENGINE_UNIT.format(account_id=account_id)),
            "port_listening": systemd_util.port_listening(ports["live_port"]),
        }
    }
