"""Provisions and controls a non-admin account's own IB Gateway + trading
engine — the instantiated systemd units (deploy/ibgateway-paper@.service
etc), one pair of processes per account, keyed by account_id (%i in the
unit name). The admin's own Gateway stays on the original fixed units
(see web/gateway_control.py) and is never touched by this module.

"Connect" (provision_and_connect) only starts the Gateway processes, not
the trading engine — mirrors gateway_control.py's own
reconnect_gateway()/resume_engine() split: IBKR may need a fresh 2FA
approval on THIS account's own phone before the Gateway actually logs in,
so the engine should only start once status() shows port_listening=True
for both modes.
"""
from pathlib import Path

from src import db, secrets_store, systemd_util

PROJECT_DIR = Path(__file__).resolve().parent.parent
IBC_DIR = PROJECT_DIR / "deploy" / "ibc"

GATEWAY_UNIT = {"paper": "ibgateway-paper@{account_id}.service", "live": "ibgateway-live@{account_id}.service"}
ENGINE_UNIT = {"paper": "trading-bot-paper@{account_id}.service", "live": "trading-bot-live@{account_id}.service"}

ProvisioningError = systemd_util.SystemctlError


class CredentialsNotSetError(RuntimeError):
    """Raised when an account tries to connect before saving IBKR
    credentials — see web/app.py's /api/ibkr_credentials."""


class AdminNotAllowedError(RuntimeError):
    """The admin already has a working Gateway on the original fixed
    units (see web/gateway_control.py) — self-provisioning through here
    too would start a SECOND, redundant Gateway process logged into the
    exact same IBKR account, which IBKR would treat as a conflicting
    session. This path is for every other account only."""


def _check_not_admin(account_id: int):
    if account_id == db.get_default_account_id():
        raise AdminNotAllowedError(
            "The admin account already has a Gateway — use the Gateway Connection card instead."
        )


def _ibc_config_path(account_id: int, mode: str) -> Path:
    return IBC_DIR / f"config-{account_id}-{mode}.ini"


def _write_ibc_config(account_id: int, mode: str, ibkr_username: str, ibkr_password: str, port: int):
    # Regenerated on every Connect click — never hand-edited, so it's
    # always in sync with whatever credentials/port this account has on
    # file right now.
    content = f"""\
# Auto-generated by src/gateway_provisioning.py for account {account_id}
# ({mode}). Regenerated every time this account clicks Connect — do not
# edit by hand, changes will be overwritten on the next Connect.
IbLoginId={ibkr_username}
IbPassword={ibkr_password}
TradingMode={mode}
OverrideTwsApiPort={port}

AcceptIncomingConnectionAction=accept
AllowBlindTrading=no
ReadOnlyLogin=no
AcceptNonBrokerageAccountWarning=yes
DismissPasswordExpiryWarning=yes
DismissNSEComplianceNotice=yes
ExistingSessionDetectedAction=primary

# IBC can automate the username/password fields but cannot tap "Approve"
# on this account's own phone for a 2FA push — this just controls how
# long IBC waits for that before giving up.
SecondFactorAuthenticationTimeout=180
SecondFactorDevice=IB Key

LogComponents=open
"""
    path = _ibc_config_path(account_id, mode)
    path.write_text(content)
    path.chmod(0o600)


def provision_and_connect(account_id: int):
    """Writes this account's IBC config (paper + live) from their saved
    credentials and starts their Gateway processes. Raises
    CredentialsNotSetError if they haven't saved IBKR credentials yet, or
    ProvisioningError if starting a unit fails (most likely the sudoers
    rules for @-instances haven't been installed on this server yet)."""
    _check_not_admin(account_id)
    creds = db.get_ibkr_credentials(account_id)
    if creds is None:
        raise CredentialsNotSetError("Save your IBKR username and password first.")

    ibkr_username = creds["ibkr_username"]
    ibkr_password = secrets_store.decrypt(creds["ibkr_password_encrypted"])
    ports = db.get_or_assign_gateway_ports(account_id)

    IBC_DIR.mkdir(parents=True, exist_ok=True)
    _write_ibc_config(account_id, "paper", ibkr_username, ibkr_password, ports["paper_port"])
    _write_ibc_config(account_id, "live", ibkr_username, ibkr_password, ports["live_port"])

    for mode in ("paper", "live"):
        unit = GATEWAY_UNIT[mode].format(account_id=account_id)
        systemd_util.run_privileged("start", unit)


def resume_engines(account_id: int):
    """Starts this account's trading engines — call only after status()
    shows port_listening=True for both modes (i.e. 2FA has actually been
    approved and the Gateway is really up)."""
    _check_not_admin(account_id)
    for mode in ("paper", "live"):
        unit = ENGINE_UNIT[mode].format(account_id=account_id)
        systemd_util.run_privileged("start", unit)


def disconnect(account_id: int):
    """Stops this account's engines first, then their Gateway — so the
    engine never sees its Gateway disappear out from under it mid-cycle."""
    _check_not_admin(account_id)
    for mode in ("paper", "live"):
        systemd_util.run_privileged("stop", ENGINE_UNIT[mode].format(account_id=account_id))
    for mode in ("paper", "live"):
        systemd_util.run_privileged("stop", GATEWAY_UNIT[mode].format(account_id=account_id))


def status(account_id: int) -> dict:
    _check_not_admin(account_id)
    ports = db.get_or_assign_gateway_ports(account_id)
    result = {}
    for mode in ("paper", "live"):
        port = ports["paper_port"] if mode == "paper" else ports["live_port"]
        result[mode] = {
            "gateway_active": systemd_util.is_active(GATEWAY_UNIT[mode].format(account_id=account_id)),
            "engine_active": systemd_util.is_active(ENGINE_UNIT[mode].format(account_id=account_id)),
            "port_listening": systemd_util.port_listening(port),
        }
    return result
